spring.application.name=back

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/gmalldb
spring.datasource.username=gmalladmin
spring.datasource.password=kdhospital

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# File Upload Size Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# Tomcat file amount = 100
server.tomcat.max-part-count=100

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1



# Upload Directory Settings
file.upload.products=${user.dir}/uploads/products/
file.upload.banners=${user.dir}/uploads/banners/

# Redis Settings - local setting
spring.data.redis.host=localhost
spring.data.redis.port=6379



# Mail Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dignak123@gmail.com
spring.mail.password=eftk ayem gezu ksoh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

# Toss Payment Secret key
toss.secret-key=test_sk_LkKEypNArW2Bjw7Xyl7NVlmeaxYG

# QueryDSL Settings
springdoc.querydsl.enabled=false
# 공공데이터포털 api key
api.serviceKey= f0bb9c59f56cc512a76eb812ddb847dec8d82dc137c8d08f81a4daefc4ad31f4
# 카카오 API
kakao.client_id=68cff17719b3c43572507fea2c172298
kakao.redirect_uri=http://localhost:5173/oauth/kakao
kakao.client_secret=XNIyrWwsmjU3YGM4xMAN5MG6NEiHAVUx

# 네이버 API
naver.client_id=WnsZfckbLjR_r3kvvmOI
naver.client_secret=wYt2oAQZLK

