spring.application.name=back
spring.profiles.active=local

# JPA (common)
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# File Upload Size Settings (common)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
server.tomcat.max-part-count=100
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

# Mail Server Settings (common)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

# QueryDSL Settings (common)
springdoc.querydsl.enabled=false


